qtl2web/modules/page/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint
from flask import current_app
from flask import redirect
from flask import render_template
from flask import request
from flask import send_from_directory
from flask import session
from flask import url_for


from qtl2web import utils
from qtl2web import tech

import os
import socket


page = Blueprint('page', __name__, template_folder='templates')


@page.route('/ping')
def ping():
    return 'OK!!!!'


@page.route('/favicon.ico')
def favicon():
    return redirect(url_for('static', filename='favicon.ico'))


@page.route('/login', methods=['GET', 'POST'])
def login():
    #print(request.form.get('frm_id'))
    #print(request.form.get('frm_pwd'))

    #print(current_app.config['LOGIN_USERID'])
    #print(current_app.config['LOGIN_PASSWORD'])

    if request.form.get('frm_pwd') == current_app.config['LOGIN_PASSWORD'] and \
            request.form.get('frm_id') == current_app.config['LOGIN_USERID']:
        session['auth'] = True
        session['auth_message'] = False
    else:
        session['auth'] = False
        session['auth_message'] = True

    if request.method == 'GET':
        # don't display a message if calling login directly
        session['auth_message'] = False

    return redirect(url_for('page.index'))


@page.route('/logout', methods=['GET', 'POST'])
def logout():
    session.clear()
    return redirect(url_for('page.index'))


@page.route('/')
def index():
    # POST search_term = request.form.get("search_term")
    # GET  search_term = request.args.get("search_term")
    # BOTH search_term = request.values.get("search_term")

    search_term = request.values.get('search_term', '')
    datasetid = request.values.get('datasetid', '')
    debug = utils.str2bool(request.values.get('debug', ''))
    admin = utils.str2bool(request.values.get('admin', ''))
    app_version = os.getenv('DOCKER_QTL2WEB_VERSION', '')

    if current_app.config['LOGIN_REQUIRED'] and not session.get('auth'):
        #print('session.get("auth")')
        #print(session.get('auth'))
        return render_template('page/login.html', debug=debug)

    return render_template('page/index.html',
                           search_term=search_term, datasetid=datasetid,
                           debug=debug, app_version=app_version, admin=admin,
                           TECHNOLOGIES=tech.TECHNOLOGIES)


'''
@page.route('/')
def home():
    print('CALL to /')
    # POST search_term = request.form.get("search_term")
    # GET  search_term = request.args.get("search_term")
    # BOTH search_term = request.values.get("search_term")
    search_term = request.values.get('search_term', '')
    datasetid = request.values.get('datasetid', '')

    print(request.cookies)

    resp = redirect('/')
    resp.set_cookie('search_term', 'NOVAL', expires=0)
    resp.set_cookie('datasetid', 'NOVAL', expires=0)

    if search_term or datasetid:

        for arg in request.args:
            if arg.lower() in ['search_term', 'datasetid']:
                resp.set_cookie('{}'.format(arg), request.args[arg])

        return resp
    else:

        if 'search_term' in request.cookies:
            search_term = request.cookies['search_term']

        if 'datasetid' in request.cookies:
            datasetid = request.cookies['datasetid']

    return render_template('page/index.html',
                           search_term=search_term, datasetid=datasetid)

'''


@page.route('/error/500')
def error():
    redirect_url = url_for('page.index')
    return render_template('errors/error.html',
                           error_code=500,
                           redirect_url=redirect_url), 500


@page.route('/_info', methods=['GET'])
def info():
    return '{}'.format(socket.gethostname())


@page.route('/dl')
def dl():
    file_name = request.values.get('fileName', '')
    return send_from_directory('/app/qtl2web/data/rdata',
                               file_name,
                               as_attachment=True)

qtl2web/modules/page/templates/page/login.html
{% extends 'layouts/base.html' %}

{% block title %}{{ config.MAIN_TITLE|safe }}{% endblock %}
{% block meta_description %}{% endblock %}
{% block head %}
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <link rel="stylesheet"
          href="{{ url_for('static', filename='vendor/please-wait-0.0.5/please-wait.css') }}">

    <link rel="stylesheet"
          href="{{ url_for('static', filename='styles/main.css') }}">

{% endblock %}

{% block body %}
<body>
    <div class="container-fluid">
        <main class="col-12" role="main">
            <div class="row justify-content-center">
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            <i class="fas fa-sign-in-alt"></i>
                            Login
                        </div>
                        <div class="card-body">
                            {% if session.auth_message %}
                            <div class="row">
                                <div class="col">
                                    <span class="text-danger">Invalid User ID or Password.</span>
                                </div>
                            </div>
                            {% endif %}
                            <div class="row">
                                <div class="col">
                                    <form id="login" name="login" method="post" action="{{ url_for('page.login') }}">
                                      <div class="form-group">
                                        <label for="frm_id">User ID</label>
                                        <input type="text" class="form-control" name="frm_id" id="frm_id" aria-describedby="idHelp" placeholder="User ID">
                                      </div>
                                      <div class="form-group">
                                        <label for="frm_pwd">Password</label>
                                        <input type="password" class="form-control" name="frm_pwd" id="frm_pwd" placeholder="Password">
                                      </div>
                                      <button type="submit" id="btn_login" class="btn btn-primary">Login</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</body>
{% endblock %}

{% block javascript %}

    <script>
    $().ready(function () {
        $('#frm_id').keypress(function(evt) {
            let code = evt.which ? evt.which : evt.keyCode;
            if (code === 13) {
                $(this).blur();
                $('#btn_login').focus().click();
            }
        });

        $('#frm_pwd').keypress(function(evt) {
            let code = evt.which ? evt.which : evt.keyCode;
            if (code === 13) {
                $(this).blur();
                $('#btn_login').focus().click();
            }
        });
    });

    </script>

{% endblock %}

qtl2web/modules/page/templates/page/test.html
{% extends 'layouts/base.html' %}

{% block title %}TEST{% endblock %}
{% block meta_description %}{% endblock %}
{% block head %}
<style>
.table-responsive .highlight pre {
    white-space: normal
}

.bd-table th small,
.responsive-utilities th small {
    display: block;
    font-weight: 400;
    color: #999
}

.responsive-utilities tbody th {
    font-weight: 400
}

.responsive-utilities td {
    text-align: center
}

.responsive-utilities .is-visible {
    color: #468847;
    background-color: #dff0d8!important
}

.responsive-utilities .is-hidden {
    color: #ccc;
    background-color: #f9f9f9!important
}

.responsive-utilities-test {
    margin-top: .25rem
}

.responsive-utilities-test .col-6 {
    margin-top: .5rem;
    margin-bottom: .5rem
}

.responsive-utilities-test span {
    display: block;
    padding: 1rem .5rem;
    font-size: 1rem;
    font-weight: 700;
    line-height: 1.1;
    text-align: center;
    border-radius: .25rem
}

.hidden-on .col-6>.not-visible,
.visible-on .col-6>.not-visible {
    color: #999;
    border: 1px solid #ddd
}

.hidden-on .col-6 .visible,
.visible-on .col-6 .visible {
    color: #468847;
    background-color: #dff0d8;
    border: 1px solid #d6e9c6
}

@media (max-width:575px) {
    .hidden-xs-only {
        display: none!important
    }
}

@media (min-width:576px) and (max-width:767px) {
    .hidden-sm-only {
        display: none!important
    }
}

@media (min-width:768px) and (max-width:991px) {
    .hidden-md-only {
        display: none!important
    }
}

@media (min-width:992px) and (max-width:1199px) {
    .hidden-lg-only {
        display: none!important
    }
}

@media (min-width:1200px) {
    .hidden-xl-only {
        display: none!important
    }
}

</style>

{% endblock %}

{% block body %}
<body>
<div class="container">

    <h2 id="test-cases">Test cases</h2>

    <p>Resize your browser or load on different devices to test the responsive utility classes.</p>

    <p>Green checkmarks indicate the element <strong>is visible</strong> in your current viewport.</p>

<div class="p-1 d-block bg-success">visible from  (1px) to xl ∞</div>
<div class="p-1 d-none d-sm-block bg-success">visible from sm (576px) to xl ∞</div>
<div class="p-1 d-none d-md-block bg-success">visible from md (768px) to xl ∞</div>
<div class="p-1 d-none d-lg-block bg-success">visible from lg (992px) to xl ∞</div>
<div class="p-1 d-none d-xl-block bg-success">visible from xl (1200px) to ∞</div>
<div class="p-1 d-sm-none bg-danger">NOT visible from sm (576px) to xl ∞</div>
<div class="p-1 d-md-none bg-danger">NOT visible from md (768px) to xl ∞</div>
<div class="p-1 d-lg-none bg-danger">NOT visible from lg (992px) to xl ∞</div>
<div class="p-1 d-xl-none bg-danger">NOT visible from xl (1200px) to ∞</div>


    <hr />


<div class="row responsive-utilities-test visible-on">
  <div class="col-6 col-sm-3">
    <span class="d-sm-none visible">&#10004; Visible on extra small</span>
    <span class="d-none d-sm-block not-visible">Extra small</span>
  </div>
  <div class="col-6 col-sm-3">
    <span class="d-md-none visible">&#10004; Visible on small or narrower</span>
    <span class="d-none d-md-block not-visible">Small or narrower</span>
  </div>
  <div class="col-6 col-sm-3">
    <span class="d-lg-none visible">&#10004; Visible on medium or narrower</span>
    <span class="d-none d-lg-block not-visible">Medium or narrower</span>
  </div>
  <div class="col-6 col-sm-3">
    <span class="d-xl-none visible">&#10004; Visible on large or narrower</span>
    <span class="d-none d-xl-block not-visible">Large or narrower</span>
  </div>
</div>

    <hr>

    <div class="row responsive-utilities-test visible-on">
      <div class="col-6 col-sm-3">
        <span class="d-none d-sm-block visible">&#10004; Visible on SM+</span>
        <span class="d-sm-none not-visible">SM+</span>
      </div>
      <div class="col-6 col-sm-3">
        <span class="d-none d-md-block visible">&#10004; Visible on MD+</span>
        <span class="d-md-none not-visible">MD+</span>
      </div>
      <div class="col-6 col-sm-3">
        <span class="d-none d-lg-block visible">&#10004; Visible on LG+</span>
        <span class="d-lg-none not-visible">LG+</span>
      </div>
      <div class="col-6 col-sm-3">
        <span class="d-none d-xl-block visible">&#10004; Visible XL+</span>
        <span class="d-xl-none not-visible">XL+</span>
      </div>
    </div>

</div>

    <hr>

<div class="row">
    <div class="col-3">
      <div class="card">
        <h4 class="card-header bg-primary">bs4-alpha</h4>
        <div class="card-body">
          <h4 class="card-title">hola</h4>
          <p class="card-text">hi</p>
          <p class="card-text">
          </p>
        </div>
      </div>
    </div>

    <div class="col-9">
      <div class="card">
        <h4 class="card-header bg-primary">bs4-beta</h4>
        <div class="card-body">
          <h4 class="card-title">title</h4>
          <p class="card-text">lskdslkjdlsjdl</i></p>
        </div>
      </div>
    </div>

  </div>

</div>
</body>
{% endblock %}

qtl2web/modules/page/templates/page/test2.html
{% extends 'layouts/base.html' %}

{% block title %}TEST{% endblock %}
{% block meta_description %}{% endblock %}
{% block head %}


{% endblock %}

{% block body %}
<body>
<div class="container">





</div>
</body>
{% endblock %}


{% block javascript %}
    <!-- please wait -->
    <script src="{{ url_for('static', filename='scripts/vendor/please-wait/please-wait.js') }}"></script>
    <script>
    window.loading_screen = window.pleaseWait({
        logo: "",
        backgroundColor: '#000000',
        //loadingHtml: "<p style='color:white' class='loading-message'>Loading...</p>"
        loadingHtml: "<div id='loader-wrapper'><div id='loader'></div><div class='loader-section section-left'></div><div class='loader-section section-right'></div></div>"
      });
    </script>


    <!-- ENSIMPL API -->
    <script src="//churchill-lab.jax.org/ensimpl/api/js/ensimpl.js"></script>

    <!-- Highcharts //-->
    <script src="//code.highcharts.com/stock/highstock.src.js"></script>
    <script src="//code.highcharts.com/highcharts-more.js"></script>
    <script src="//code.highcharts.com/modules/boost.src.js"></script>
    <script src="//code.highcharts.com/modules/exporting.js"></script>
    <script src="//code.highcharts.com/modules/canvas-tools.src.js"></script>

    <!-- D3 //-->
    <script src="//d3js.org/d3.v3.min.js"></script>
    <script src="//d3js.org/d3-queue.v3.js"></script>
    <script src="//d3js.org/d3-collection.v1.min.js"></script>
    <script src="//d3js.org/d3-dispatch.v1.min.js"></script>
    <script src="//d3js.org/d3-dsv.v1.min.js"></script>
    <script src="//d3js.org/d3-request.v1.min.js"></script>

    <!-- DataTables
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    //-->

    <!-- Extra //-->
    <script src="{{ url_for('static', filename='scripts/vendor/factexpviewer.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/ToProgress-0.1.1/ToProgress.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/js.cookie-2.2.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/seedrandom-2.4.3/seedrandom.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/jquery-typeahead-2.10.4/jquery.typeahead.min.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/vendor/jquery.popupoverlay.js') }}"></script>

    <script>


        /**
         * Perform gene search.
         */
        function selectGeneProtein(geneID, proteinID, datasetID) {
            d3.queue()
                .defer(downloadGeneData, geneID)
                .defer(downloadLODData, id, level, regressLocal)
                .defer(downloadProfileData, id, level)
                .await(function(error, geneData, lodData, profileData) {
                    if (error) {
                        let message = 'Unable to download data for <strong><em>';
                        message += id;
                        message += '</em></strong>.';

                        unblockUser();
                        displayError('API Server Error', message);

                        console.error('error=', error);
                        console.error(message);
                        return;
                    }

                    _G.current_gene = geneData[0];
                    _G.current_gene_id = geneID;
                    _G.current_protein_id = proteinID;
                    displayGeneData(_G.current_gene);
                    resetSecondaryPlots();
                    _G.slider.reset();

                    plotLOD(lodData.data, id, level);
                    plotProfile(id, profileData, getFactorOrder());
                    //addHistory(_G.current_gene_id, _G.current_protein_id, geneData[0]['symbol'], level);
                    //buildHistory();
                    unblockUser();
                });

            }


function delayedHello(name, delay, callback) {
  var id = setTimeout(function() {
    console.log("Hello, " + name + "!");
    callback(null);
  }, delay);
  console.log(id);
  return {
    abort: function() {
        console.log('clearing');
      clearTimeout(id);
    }
  };
}
var q = null;

        // call whoa to abort q
        function whoa() {
            try { q.abort(); }
            catch (e) {
                console.log(e);
            }
        }

    $().ready(function () {
console.log('hello');
 q = d3.queue()
    .defer(d3.request, "https://httpbin.org/delay/10")
    .defer(d3.request, "https://httpbin.org/delay/10")
    .defer(d3.request, "https://httpbin.org/delay/10")
    .awaitAll(function(error, results) {
      if (error) throw error;
      console.log(results);
    });


    });




    </script>

{% endblock %}